name: GoldPiglin
version: '${version}'
main: one.pkg.goldpiglin.GoldPiglin
api-version: '1.20'
folia-supported: true
load: STARTUP
softdepend: [Rtag, NBTAPI]
authors: [404Setup]
website: https://github.com/404Setup/GoldPiglin
permissions:
  goldpiglin.command.reload:
    default: op
  goldpiglin.command.version:
    default: op
  goldpiglin.update_message:
    default: op