name: GoldPiglin
version: '${version}'
main: one.tranic.goldpiglin.GoldPiglin
api-version: '1.20'
folia-supported: true
load: STARTUP
depend: [NBTAPI]
authors: [404Setup]
website: https://hangar.papermc.io/404
permissions:
  goldpiglin.command.greload:
    default: op
