name: GoldPiglin
version: '${version}'
main: one.tranic.goldpiglin.GoldPiglin
api-version: '1.20'
folia-supported: true
load: STARTUP
softdepend: [NBTAPI]
authors: [404Setup]
website: https://hangar.papermc.io/404
permissions:
  goldpiglin.command.reload:
    default: op
  goldpiglin.command.version:
    default: op
  goldpiglin.update_message:
    default: op